spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root123
    dbcp:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    hibernate:
      #ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
